version: '2.4'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-jcr:7.39.4
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
    - "./artifactory/:/artifactory_extra_conf/"
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
        interval: 5s
        timeout: 10s
        retries: 30
        start_period: 30s

  jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_controller/casc.yml/:/usr/share/jenkins/ref/casc.yml"
      - "./jenkins_controller/jobs:/usr/share/jenkins/ref/jobs"
    restart: always

  jenkins_agent:
    depends_on:
      - jenkins
    build: jenkins_agent
    container_name: jenkins_agent
    ports:
      - "2222:22"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDhyeROg2/ntEMxiK/f8Hz6X5LuARJbf9H2yyIDc2Y6Blzzj0b0NZ4IY8xMtUNMlxu6S6PHoSO5K/VoaXqW3SnK/Iuwx7yJYkNV6S+n+H9sFcMpMjHgJ54pgB802TYampIHu2UQc6Ib27bBjrebsyJIpkXGuc/Fn80Z+CZ8sQ25CnHpe/u35iolj0hN+A2K/ys7YU7SiTtGPsfJGlQ5690kk5PTsWQpqNQbghONYUS41f90qx9bzp/pFvGQb+59gJjeJHqx7Bk++LwLzqgTblZFDmmM2ci5jbnggY+4JMKjxCGzeCO+/CAS/qF7Jnn/G7GBBTdPRn8nsJImhaBQSU3ElNd9dsOpx4b7RUcO0pUJGiY26lSEDyEl0mKLfPxiFoFa72rxkzJqbgbUrO1qQyrUlaFQ1QGOX+mUIkc0RoEaCEhbdryzW+KJU41xq405/t1MiUrVLyyKJxXBHsmiBOnL+1/rZUGLmR62KyvuZxNiBKnio9Uk+0oCu2Kb52uTU+c= panda@vagrant
    restart: always

  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:9.2.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always
  
  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always

  selenium_node:
    depends_on:
      - selenium_hub
    image: selenium/node-firefox
    container_name: firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always
  
  

